version: '3'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my-database
    ports:
      - '5432:5432'
